version:
  name: velociraptor
  version: 0.3.6
  commit: 089cf7c
  build_time: "2019-11-20T21:50:38+10:00"
Client:
  server_urls:
  - https://192.168.33.102:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDKzCCAhOgAwIBAgIRAImViQYCMPgHR6NHoDKrJqcwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIwMDEwNjEzNDkwN1oXDTIx
    MDEwNTEzNDkwN1owGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6+ykq45YBtpr+p42NzfbJgJutsqSgyf8
    BZ/SlC29KlNGQ4Z85NJ+B5sUgOZQWuPWbZJAhKzwCxpJJjfFUGvstSfR735hYW6u
    NakWTBfRh74qQ252g5ov7rDyvugnMDfmTSBu0hjEWIdHX58bbfFbEFj9e09FmTae
    uCCJ9cs/09kYshAZYZuGehnsIoHz4I31iWhGdNSibbnJlDsMmyrLsxB0F3MWPzaH
    IlVopiB1BYmzhlz0gf5TiJwWXcslYM+waqn8YjzJXW8ug9NU3BcsvCP7YiE0+bty
    iVi9NLXglKOvEVgLoP2KRuvB/rmwOwyyUhZOdNFcvt4czBuDaSw2cQIDAQABo2ww
    ajAOBgNVHQ8BAf8EBAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
    MA8GA1UdEwEB/wQFMAMBAf8wKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZl
    bG9jaWRleC5jb20wDQYJKoZIhvcNAQELBQADggEBAI8UER2e3CpOE8ZjuMPlo7hi
    IXCeEhpCkHRxqPnpnYrNmn5Vp4Wo2wAKf/DZvl3gP6yAggbI+8rVLDxebXdVgPHf
    0jkKfoY6xM0Vbo4Q3lNGcnd4OdzNFC0tb+g9MJ5JL6xDs6q9h2zTRc62apAE52uh
    5sWoU2CRCDhuObOGQccVehdZNmk2bemeVb29oj94bbJD+/mwbqGSVIA+I/417+ju
    SaNs705WcOnl66SN5Gj7Jm6HDV3uN+Myr6Iy1DP8+G2Q8LCnrVeWYzYUt30awPKb
    G68sy8mrtMgUCftxvmOg1itmQXaJRRbjDwKi0JzbxbEIBuXjPV5or+ugGpm+nbA=
    -----END CERTIFICATE-----
  nonce: RPStXzPHoGg=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  max_poll: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.3.6
    commit: 089cf7c
    build_time: "2019-11-20T21:50:38+10:00"
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename: $Temp/Velociraptor_Buffer.bin
